.DEFAULT_GOAL = install

clean:
	rm -fr .venv install

.venv:
	uv venv

upgrade: .venv
	uv pip install --upgrade

install: .venv requirements.txt
	uv pip install --requirements ./requirements.txt
	touch install
